### ISSUE TITLE
Router - Get pod IP on EKS

### ISSUE THREAD

**Issue by huntharo** [pwrdrvr/lambda-dispatch#153]
## Motivations

- Neither the EC2 nor ECS metadata response types will have the container IP
- https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-eks-supports-ec2-instance-metadata-service-v2/#:~:text=Amazon%20EKS%20now%20supports%20containerized%20applications%20that%20require,to%20EC2%20instance%20metadata%20using%20the%20IMDSv2%20format

## Acceptance Criteria

- [x] Initial version using hard-coded env name K8S_POD_IP - Handled by #152 
- [x] Allow specifying the Env Var name to check for the IP

## K8S Downward API - Inject Pod IP

```
env:
  - name: K8S_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
```
